title: Alida Horsley
description: UX & Product Designer — case studies, writing, and UX resources.
url: ""
baseurl: ""

sass:
  style: compressed

exclude:
  - _archive
  - deploy
  - Gemfile
  - Gemfile.lock
  - README.md
